# yaml-language-server: $schema=../node_modules/somod/node_modules/@somod/serverless-schema/schemas/index.json

Resources:
  BaseHttpApi:
    Type: AWS::Serverless::HttpApi
    "SOMOD::Access": "public"
    "SOMOD::Output":
      default: true
      attributes: []
      export:
        default: apigateway.http.id
    Properties: {}
